Hw8
oleomarek/python_basic_course pull request #8
Opened 2018-04-20 05:59 UTC by oleomarek

Final_project Done!

2018-04-21 11:28 UTC, withoutremorce approved these changes
😁  good!

2018-04-23 18:43 UTC, voronov007 requested changes

2018-04-23 18:43 UTC, voronov007 commented on final_project/utils.py
> +number = (44, 50, 63, 68, 73, 91, 93, 94, 95)
а почему берешь эти цифры? почему это пара цифр? ведь можно брать любые цифры от 0 до 9 рандомно.

2018-04-23 18:43 UTC, voronov007 commented on final_project/utils.py
> +number = (44, 50, 63, 68, 73, 91, 93, 94, 95)
а, это кода операторов. Теперь я понял. Но где-то я этот код уже видел ))

2018-04-23 18:43 UTC, voronov007 commented on final_project/utils.py
> +    card = list(''.join(choice(digits) for i in range(4)) +
переделай эту чатсь. Она повторяется у Жени

2018-04-23 18:43 UTC, voronov007 commented on final_project/utils.py
> +    card = card[0:4] + ' ' + card[4:8] + ' ' + card[8:12] + ' ' + card[12:16]
и иэту часть переделай. Попробуй сделать что-то свое.

2018-04-23 18:43 UTC, voronov007 commented on final_project/utils.py
> +    card_cred = re.search(r'[a-zA-Z\ ]', (rand_cred.get("Card")[0:4]+rand_cred.get("Card")[5:9]+rand_cred.get("Card")[10:14]+rand_cred.get("Card")[15:19]))
совсем некрасивая эта часть. и мы уже писали нормальную проверку, посмотри у других и возьми уже готовую. проверку.

2018-04-23 18:43 UTC, voronov007 commented
Попробуй создать свое решение некоторых спорных моментов, которые такие же как у Жени

2018-04-26 13:05 UTC, closed without merging